package com.arisamtunes.core.design.colors

import androidx.compose.ui.graphics.Color

internal val LightPrimary = Color(0xFF0369A1)
internal val LightPrimaryVariant = Color(0xFF075985)
internal val LightSecondary = Color(0xFF0369A1)
internal val LightSecondaryContainer = Color(0xFFD7F0FE)
internal val LightOnSecondaryContainer = Color(0xFF082F49)
internal val LightTertiary = Color(0xFF6D28D9)
internal val LightTertiaryContainer = Color(0xFFEDE9FE)
internal val LightOnTertiaryContainer = Color(0xFF3B0764)
internal val LightBackground = Color(0xFFF0F9FF)
internal val LightSurface = Color(0xFFFFFFFF)
internal val LightTextPrimary = Color(0xFF0C4A6E)
internal val LightTextSecondary = Color(0xFF0369A1)
internal val LightBorder = Color(0xFFBAE6FD)
internal val LightSurfaceVariant = Color(0xFFE0F2FE)
internal val LightSurfaceContainerHighest = Color(0xFFD4EAF5)
internal val LightErrorContainer = Color(0xFFFFDAD6)
internal val LightOnErrorContainer = Color(0xFF410002)

internal val DarkPrimary = Color(0xFF38BDF8)
internal val DarkOnPrimary = Color(0xFF082F49)
internal val DarkPrimaryVariant = Color(0xFF0369A1)
internal val DarkSecondary = Color(0xFF7DD3FC)
internal val DarkSecondaryContainer = Color(0xFF0C4A6E)
internal val DarkOnSecondaryContainer = Color(0xFFE0F2FE)
internal val DarkTertiary = Color(0xFFC4B5FD)
internal val DarkTertiaryContainer = Color(0xFF4C1D95)
internal val DarkOnTertiaryContainer = Color(0xFFEDE9FE)
internal val DarkBackground = Color(0xFF0C1821)
internal val DarkSurface = Color(0xFF1E2A3A)
internal val DarkTextPrimary = Color(0xFFF0F9FF)
internal val DarkTextSecondary = Color(0xFFBAE6FD)
internal val DarkBorder = Color(0xFF0369A1)
internal val DarkSurfaceVariant = Color(0xFF26364A)
internal val DarkSurfaceContainerHighest = Color(0xFF304454)
internal val DarkErrorContainer = Color(0xFF93000A)
internal val DarkOnError = Color(0xFF690005)
internal val DarkOnErrorContainer = Color(0xFFFFDAD6)
internal val TehranAmber = Color(0xFFFFC857)
internal val TehranAmberInk = Color(0xFF332300)
internal val ErrorDark = Color(0xFFFFB4AB)
internal val ErrorLight = Color(0xFFBA1A1A)
