ktor {
    deployment {
        host = "0.0.0.0"
        port = 8080
        port = ${?PORT}
    }

    application {
        modules = [ com.arisamtunes.ApplicationKt.module ]
    }
}

app {
    publicBaseUrl = "http://localhost:8080"
    publicBaseUrl = ${?PUBLIC_BASE_URL}
}

database {
    enabled = true
    enabled = ${?DB_ENABLED}
    host = "localhost"
    host = ${?DB_HOST}
    port = 5432
    port = ${?DB_PORT}
    name = "arisam_tunes_db"
    name = ${?DB_NAME}
    user = "arisam"
    user = ${?DB_USER}
    password = "arisam_dev_password"
    password = ${?DB_PASSWORD}
}
